# Generated by Django 3.0.3 on 2020-06-05 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Taskdata',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('temperature', models.CharField(max_length=250)),
                ('duration', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'taskdata',
            },
        ),
    ]
