name: DataTask

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11-alpine
        env:
          POSTGRES_USER: admin1
          POSTGRES_PASSWORD: admin1
        ports:
          - "5432:5432"
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 10

    steps:
      - uses: actions/checkout@v2
      - run: mkdir -p DataTask/htmlcov/report.html
      - name: Configure GPG Key
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          git-user-signingkey: true
          git-commit-gpgsign: true
      - name: Reveal secrets
        env:
          SECRET_PWD: ${{ secrets.PASSPHRASE }}
        run: |
          sudo apt install git-secret
          git secret reveal
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv shell
          pipenv run

      - name: Coverage report
        run: |
          pip install coverage
          coverage run manage.py test showdata
          coverage report
      - name: Django Testing
        run: python3 manage.py test showdata

      - name: Archive codes coverage results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: DataTask/htmlcov/report.html
